from enum import StrEnum, auto


class Country(StrEnum):
    AFG = auto()  # AFGHANISTAN
    ALB = auto()  # ALBANIA
    AND = auto()  # ANDORRA
    AGO = auto()  # ANGOLA
    AIA = auto()  # ANGUILLA
    ATG = auto()  # ANTIGUA AND BARBUDA
    ARG = auto()  # ARGENTINA
    ARM = auto()  # ARMENIA
    ABW = auto()  # ARUBA
    AUS = auto()  # AUSTRALIA
    AUT = auto()  # AUSTRIA
    AZE = auto()  # AZERBAIJAN
    BHS = auto()  # BAHAMAS
    BRB = auto()  # BARBADOS
    BLR = auto()  # BELARUS
    BEL = auto()  # BELGIUM
    BLZ = auto()  # BELIZE
    BEN = auto()  # BENIN
    BOL = auto()  # BOLIVIA
    BIH = auto()  # BOSNIA AND HERZEGOVINA
    BWA = auto()  # BOTSWANA
    BRA = auto()  # BRAZIL
    BRN = auto()  # BRUNEI
    BGR = auto()  # BULGARIA
    BDI = auto()  # BURUNDI
    KHM = auto()  # CAMBODIA
    CMR = auto()  # CAMEROON
    CAN = auto()  # CANADA
    CPV = auto()  # CAPE VERDE
    CYM = auto()  # CAYMAN ISLANDS
    CHL = auto()  # CHILE
    CHN = auto()  # CHINA - CHINA
    HKG = auto()  # CHINA - SAR HONGKONG
    MAC = auto()  # CHINA - SAR MACAU
    COL = auto()  # COLOMBIA
    COM = auto()  # COMOROS
    COK = auto()  # COOK ISLANDS
    CRI = auto()  # COSTA RICA
    CIV = auto()  # COTE D\'IVOIRE
    HRV = auto()  # CROATIA
    CUB = auto()  # CUBA
    CYP = auto()  # CYPRUS
    CZE = auto()  # CZECH REPUBLIC
    DNK = auto()  # DENMARK
    DJI = auto()  # DJIBOUTI
    DMA = auto()  # DOMINICA
    DOM = auto()  # DOMINICAN REPUBLIC
    TLS = auto()  # EAST TIMOR (DEMOCRATIC REPUBLIC OF)
    ECU = auto()  # ECUADOR
    SLV = auto()  # EL SALVADOR
    GNQ = auto()  # EQUATORIAL GUINEA
    ERI = auto()  # ERITREA
    EST = auto()  # ESTONIA
    SWZ = auto()  # ESWATINI
    FJI = auto()  # FIJI
    FIN = auto()  # FINLAND
    FRA = auto()  # FRANCE
    GAB = auto()  # GABON
    GMB = auto()  # GAMBIA
    GEO = auto()  # GEORGIA
    DEU = auto()  # GERMANY
    GHA = auto()  # GHANA
    GIB = auto()  # GIBRALTAR
    GRC = auto()  # GREECE
    GRD = auto()  # GRENADA
    GTM = auto()  # GUATEMALA
    GGY = auto()  # GUERNSEY
    GIN = auto()  # GUINEA
    GUY = auto()  # GUYANA
    HTI = auto()  # HAITI
    HND = auto()  # HONDURAS
    HUN = auto()  # HUNGARY
    ISL = auto()  # ICELAND
    IND = auto()  # INDIA
    IDN = auto()  # INDONESIA
    IRL = auto()  # IRELAND
    IMN = auto()  # ISLE OF MAN
    ISR = auto()  # ISRAEL
    ITA = auto()  # ITALY
    JAM = auto()  # JAMAICA
    JPN = auto()  # JAPAN
    JEY = auto()  # JERSEY
    JOR = auto()  # JORDAN
    KAZ = auto()  # KAZAKHSTAN
    KEN = auto()  # KENYA
    KIR = auto()  # KIRIBATI
    KGZ = auto()  # KYRGYZSTAN
    LAO = auto()  # LAOS
    LVA = auto()  # LATVIA
    LSO = auto()  # LESOTHO
    LBR = auto()  # LIBERIA
    LIE = auto()  # LIECHTENSTEIN
    LTU = auto()  # LITHUANIA
    LUX = auto()  # LUXEMBOURG
    MDG = auto()  # MADAGASCAR
    MWI = auto()  # MALAWI
    MYS = auto()  # MALAYSIA
    MLI = auto()  # MALI
    MLT = auto()  # MALTA
    MHL = auto()  # MARSHALL ISLANDS
    MUS = auto()  # MAURITIUS
    MEX = auto()  # MEXICO
    FSM = auto()  # MICRONESIA (FEDERATED STATES OF)
    MDA = auto()  # MOLDOVA
    MCO = auto()  # MONACO
    MNG = auto()  # MONGOLIA
    MNE = auto()  # MONTENEGRO
    MSR = auto()  # MONTSERRAT
    MAR = auto()  # MOROCCO
    MOZ = auto()  # MOZAMBIQUE
    MMR = auto()  # MYANMAR
    NAM = auto()  # NAMIBIA
    NRU = auto()  # NAURU
    NLD = auto()  # NETHERLANDS
    NZL = auto()  # NEW ZEALAND
    NIC = auto()  # NICARAGUA
    NER = auto()  # NIGER
    NIU = auto()  # NIUE ISLAND
    NOR = auto()  # NORWAY
    OMN = auto()  # OMAN
    PLW = auto()  # PALAU
    PSE = auto()  # PALESTINE
    PAN = auto()  # PANAMA
    PNG = auto()  # PAPUA NEW GUINEA
    PRY = auto()  # PARAGUAY
    PER = auto()  # PERU
    PHL = auto()  # PHILIPPINES
    POL = auto()  # POLAND
    PRT = auto()  # PORTUGAL
    KOR = auto()  # REPUBLIC OF KOREA
    MKD = auto()  # REPUBLIC OF NORTH MACEDONIA
    ROU = auto()  # ROMANIA
    RUS = auto()  # RUSSIAN FEDERATION
    RWA = auto()  # RWANDA
    KNA = auto()  # SAINT KITTS AND NEVIS
    LCA = auto()  # SAINT LUCIA
    VCT = auto()  # SAINT VINCENT AND THE GRENADINES
    SMR = auto()  # SAN MARINO
    SAU = auto()  # SAUDI ARABIA
    SEN = auto()  # SENEGAL
    SRB = auto()  # SERBIA
    SYC = auto()  # SEYCHELLES
    SLE = auto()  # SIERRA LEONE
    SGP = auto()  # SINGAPORE
    SVK = auto()  # SLOVAKIA
    SVN = auto()  # SLOVENIA
    SLB = auto()  # SOLOMON ISLANDS
    ZAF = auto()  # SOUTH AFRICA
    ESP = auto()  # SPAIN
    LKA = auto()  # SRI LANKA
    SUR = auto()  # SURINAME
    SWE = auto()  # SWEDEN
    CHE = auto()  # SWITZERLAND
    TWN = auto()  # TAIWAN
    TJK = auto()  # TAJIKISTAN
    TZA = auto()  # TANZANIA
    THA = auto()  # THAILAND
    TGO = auto()  # TOGO
    TON = auto()  # TONGA
    TTO = auto()  # TRINIDAD AND TOBAGO
    TCA = auto()  # TURKS AND CAICOS ISLANDS
    TUV = auto()  # TUVALU
    UGA = auto()  # UGANDA
    UKR = auto()  # UKRAINE
    ARE = auto()  # UNITED ARAB EMIRATES
    GBR = auto()  # UNITED KINGDOM
    USA = auto()  # UNITED STATES OF AMERICA
    URY = auto()  # URUGUAY
    UZB = auto()  # UZBEKISTAN
    VUT = auto()  # VANUATU
    VAT = auto()  # VATICAN CITY STATE (HOLY SEE)
    VEN = auto()  # VENEZUELA
    VNM = auto()  # VIETNAM
    WSM = auto()  # WEST SAMOA
    ZMB = auto()  # ZAMBIA
    ZWE = auto()  # ZIMBABWE
