from enum import StrEnum


class EducationInd(StrEnum):
    BELOW_MATRICULATION = "BELOW MATRICULATION"
    GRADUATE = "GRADUATE"
    HIGHER_SECONDARY = "HIGHER SECONDARY"
    ILLITERATE = "ILLITERATE"
    MATRICULATION = "MATRICULATION"
    NA_BEING_MINOR = "NA BEING MINOR"
    OTHERS = "OTHERS"
    POST_GRADUATE = "POST GRADUATE"
    PROFESSIONAL = "PROFESSIONAL"
