"""Initaial

Revision ID: 3050a3d1a3d2
Revises: 312fe2ebb0fd
Create Date: 2024-11-06 15:52:50.899970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3050a3d1a3d2'
down_revision: str | None = '312fe2ebb0fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created', nullable=False, new_column_name='created_at')
    op.alter_column('orders', 'updated', nullable=False, new_column_name='updated_at')
    op.alter_column('users', 'created', nullable=False, new_column_name='created_at')
    op.alter_column('users', 'updated', nullable=False, new_column_name='updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at', nullable=False, new_column_name='created')
    op.alter_column('orders', 'updated_at', nullable=False, new_column_name='updated')
    op.alter_column('users', 'created_at', nullable=False, new_column_name='created')
    op.alter_column('users', 'updated_at', nullable=False, new_column_name='updated')
    # ### end Alembic commands ###
