version: '3.8'
volumes:
  pgdb_data:
  pgadmin_data:
  redis_data:
  rabbitmq_data:
  grafana_data:

services:
  pgdb:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - pgdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB__USERNAME}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__DATABASE}
    ports:
      - "${DB__PORT:-5432}:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN__EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN__PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    ports:
      - "${PGADMIN__PORT:-5050}:80"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS__PASSWORD}
      REDIS_PORT: 6379
      REDIS_DATABASES: 4
    command: >
      sh -c "
        exec redis-server
          --bind 0.0.0.0
          --port $REDIS_PORT
          --requirepass $REDIS_PASSWORD
          --databases $REDIS_DATABASES
      "
    ports:
      - "${REDIS__PORT:-6379}:6379"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP__USERNAME}
      RABBITMQ_DEFAULT_PASS: ${AMQP__PASSWORD}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 262144
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "${AMQP__PORT:-5672}:5672"
      - "${AMQP_MGMT__PORT:-15672}:15672"

  bot:
    image: ghcr.io/robot-in-sky/myfirstbot:dev
    restart: always
    environment:
      DB__HOST: pgdb
      DB__PORT: ${DB__PORT:-5432}
      DB__USERNAME: ${DB__USERNAME}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__DATABASE: ${DB__DATABASE}
      REDIS__HOST: redis
      REDIS__PORT: ${REDIS__PORT:-6379}
      REDIS__USERNAME: ${REDIS__USERNAME}
      REDIS__PASSWORD: ${REDIS__PASSWORD}
      REDIS__DATABASE: ${REDIS__DATABASE}
      TGBOT__TOKEN: ${TGBOT__TOKEN}
      AMQP__HOST: rabbitmq
      AMQP__PORT:  ${AMQP__PORT:-5672}
      AMQP__USERNAME: ${AMQP__USERNAME}
      AMQP__PASSWORD: ${AMQP__PASSWORD}
      S3__URL: ${S3__URL}
      S3__BUCKET_NAME: ${S3__BUCKET_NAME}
      S3__ACCESS_KEY: ${S3__ACCESS_KEY}
      S3__SECRET_KEY: ${S3__SECRET_KEY}
      DEFAULT_ADMINS: ${DEFAULT_ADMINS}
      LOG__LEVEL: ${LOG__LEVEL:-INFO}
    depends_on:
      - pgdb
      - redis
      - rabbitmq
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  recognizer:
    image: ghcr.io/robot-in-sky/recognizer:dev
    restart: always
    environment:
      AMQP__HOST: rabbitmq
      AMQP__PORT: ${AMQP__PORT:-5672}
      AMQP__USERNAME: ${AMQP__USERNAME}
      AMQP__PASSWORD: ${AMQP__PASSWORD}
      S3__URL: ${S3__URL}
      S3__BUCKET_NAME: ${S3__BUCKET_NAME}
      S3__ACCESS_KEY: ${S3__ACCESS_KEY}
      S3__SECRET_KEY: ${S3__SECRET_KEY}
      LOG__LEVEL: ${LOG__LEVEL:-INFO}
    depends_on:
      - rabbitmq
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
