version: '3.8'
volumes:
  pgdata:
  redisdata:
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: 1qazxsw2
      POSTGRES_DB: myfirstbot
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redisdata:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: "redis-server /usr/local/etc/redis/redis.conf --requirepass 1qazxsw2"
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
