version: '3.8'
volumes:
  pgdb-data:
  redis-data:
  rabbitmq-data:
services:
  pgdb:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - pgdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB__USERNAME}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__DATABASE}
    ports:
      - "${DB__PORT}:5432"
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
      - ./deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS__PASSWORD}
      REDIS_PORT: 6379
      REDIS_DATABASES: 8
    ports:
      - "${REDIS__PORT}:6379"
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "${AMQP__PORT}:5672"
      - "15672:15672"
