version: "3.8"
services:
  redis:
    build:
      context: buildfiles
      dockerfile: redis.dockerfile
    env_file:
      - env/.env
    restart: always
    ports:
      - "6379:6379"
  db:
    image: postgres:15-alpine
    env_file:
      - env/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
  bot:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile
    env_file:
      - env/.env
    restart: always
    depends_on:
      - db
      - redis
