version: '3.8'
volumes:
  pgdb_data:
  redis_data:
  rabbitmq_data:
services:
  pgdb:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - pgdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB__USERNAME}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__DATABASE}
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
