version: '3.8'
volumes:
  pgdb-data:
  pgadmin-data:
  redis-data:
  rabbitmq-data:
services:
  pgdb:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - pgdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB__USERNAME}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__DATABASE}
    ports:
      - "${DB__PORT}:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN__EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN__PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./deploy/pgadmin/servers.json.template:/pgadmin4/servers.json.template
      - ./deploy/pgadmin/entrypoint.sh:/pgadmin4/entrypoint.sh
    restart: unless-stopped
    ports:
      - "${DB_ADMIN__PORT}:80"
    # entrypoint: /pgadmin4/entrypoint.sh
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
      - ./deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      REDIS_PASSWORD: ${REDIS__PASSWORD}
      REDIS_PORT: 6379
      REDIS_DATABASES: 8
    ports:
      - "${REDIS__PORT}:6379"
  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP__USERNAME}
      RABBITMQ_DEFAULT_PASS: ${AMQP__PASSWORD}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 262144
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "${AMQP__PORT}:5672"
      - "${AMQP_ADMIN__PORT}:15672"
  bot:
    image: ghcr.io/robot-in-sky/myfirstbot:master
    restart: always
    environment:
      DB__HOST: pgdb
      DB__PORT: ${DB__PORT}
      DB__USERNAME: ${DB__USERNAME}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__DATABASE: ${DB__DATABASE}
      REDIS__HOST: redis
      REDIS__PORT: ${REDIS__PORT}
      REDIS__USERNAME: ${REDIS__USERNAME}
      REDIS__PASSWORD: ${REDIS__PASSWORD}
      REDIS__DATABASE: ${REDIS__DATABASE}
      TGBOT__TOKEN: ${TGBOT__TOKEN}
      AMQP__HOST: rabbitmq
      AMQP__PORT:  ${AMQP__PORT}
      AMQP__USERNAME: ${AMQP__USERNAME}
      AMQP__PASSWORD: ${AMQP__PASSWORD}
      S3__URL: ${S3__URL}
      S3__BUCKET_NAME: ${S3__BUCKET_NAME}
      S3__ACCESS_KEY: ${S3__ACCESS_KEY}
      S3__SECRET_KEY: ${S3__SECRET_KEY}
      DEFAULT_ADMINS: ${DEFAULT_ADMINS}
      LOG__LEVEL: ${LOG__LEVEL}
    depends_on:
      - pgdb
      - redis
      - rabbitmq
  recognizer:
    image: ghcr.io/robot-in-sky/recognizer:master
    restart: always
    environment:
      AMQP__HOST: rabbitmq
      AMQP__PORT: ${AMQP__PORT}
      AMQP__USERNAME: ${AMQP__USERNAME}
      AMQP__PASSWORD: ${AMQP__PASSWORD}
      S3__URL: ${S3__URL}
      S3__BUCKET_NAME: ${S3__BUCKET_NAME}
      S3__ACCESS_KEY: ${S3__ACCESS_KEY}
      S3__SECRET_KEY: ${S3__SECRET_KEY}
      LOG__LEVEL: ${LOG__LEVEL}
    depends_on:
      - rabbitmq
