"""Initial

Revision ID: 2117314a5e45
Revises: 
Create Date: 2025-03-02 15:51:47.217280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2117314a5e45'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'PENDING', 'ACCEPTED', 'COMPLETED', 'TRASH', name='visaformstatus').create(op.get_bind())
    sa.Enum('AUS', 'AUT', 'AZE', 'ALA', 'ALB', 'DZA', 'VIR', 'ASM', 'AIA', 'AGO', 'AND', 'ATA', 'ATG', 'ARG', 'ARM', 'ABW', 'AFG', 'BHS', 'BGD', 'BRB', 'BHR', 'BLZ', 'BLR', 'BEL', 'BEN', 'BMU', 'BGR', 'BOL', 'BES', 'BIH', 'BWA', 'BRA', 'IOT', 'VGB', 'BRN', 'BFA', 'BDI', 'BTN', 'VUT', 'VAT', 'GBR', 'HUN', 'VEN', 'UMI', 'TLS', 'VNM', 'GAB', 'HTI', 'GUY', 'GMB', 'GHA', 'GLP', 'GTM', 'GUF', 'GIN', 'GNB', 'DEU', 'GGY', 'GIB', 'HND', 'HKG', 'GRD', 'GRL', 'GRC', 'GEO', 'GUM', 'DNK', 'JEY', 'DJI', 'DMA', 'DOM', 'COD', 'EGY', 'ZMB', 'ESH', 'ZWE', 'ISR', 'IND', 'IDN', 'JOR', 'IRQ', 'IRN', 'IRL', 'ISL', 'ESP', 'ITA', 'YEM', 'CPV', 'KAZ', 'CYM', 'KHM', 'CMR', 'CAN', 'QAT', 'KEN', 'CYP', 'KGZ', 'KIR', 'TWN', 'PRK', 'CHN', 'CCK', 'COL', 'COM', 'CRI', 'CIV', 'CUB', 'KWT', 'CUW', 'LAO', 'LVA', 'LSO', 'LBR', 'LBN', 'LBY', 'LTU', 'LIE', 'LUX', 'MUS', 'MRT', 'MDG', 'MYT', 'MAC', 'MKD', 'MWI', 'MYS', 'MLI', 'MDV', 'MLT', 'MAR', 'MTQ', 'MHL', 'MEX', 'FSM', 'MOZ', 'MDA', 'MCO', 'MNG', 'MSR', 'MMR', 'NAM', 'NRU', 'NPL', 'NER', 'NGA', 'NLD', 'NIC', 'NIU', 'NZL', 'NCL', 'NOR', 'ARE', 'OMN', 'BVT', 'IMN', 'COK', 'NFK', 'CXR', 'PCN', 'SHN', 'PAK', 'PLW', 'PSE', 'PAN', 'PNG', 'PRY', 'PER', 'POL', 'PRT', 'PRI', 'COG', 'KOR', 'REU', 'RUS', 'RWA', 'ROU', 'SLV', 'WSM', 'SMR', 'STP', 'SAU', 'MNP', 'SYC', 'BLM', 'MAF', 'SPM', 'SEN', 'VCT', 'KNA', 'LCA', 'SRB', 'SGP', 'SXM', 'SYR', 'SVK', 'SVN', 'SLB', 'SOM', 'SDN', 'SUR', 'USA', 'SLE', 'TJK', 'THA', 'TZA', 'TCA', 'TGO', 'TKL', 'TON', 'TTO', 'TUV', 'TUN', 'TKM', 'TUR', 'UGA', 'UZB', 'UKR', 'WLF', 'URY', 'FRO', 'FJI', 'PHL', 'FIN', 'FLK', 'FRA', 'PYF', 'ATF', 'HMD', 'HRV', 'CAF', 'TCD', 'MNE', 'CZE', 'CHL', 'CHE', 'SWE', 'SJM', 'LKA', 'ECU', 'GNQ', 'ERI', 'SWZ', 'EST', 'ETH', 'ZAF', 'SGS', 'SSD', 'JAM', 'JPN', name='country').create(op.get_bind())
    sa.Enum('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='userrole').create(op.get_bind())
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('role', postgresql.ENUM('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='userrole', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('visas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('country', postgresql.ENUM('AUS', 'AUT', 'AZE', 'ALA', 'ALB', 'DZA', 'VIR', 'ASM', 'AIA', 'AGO', 'AND', 'ATA', 'ATG', 'ARG', 'ARM', 'ABW', 'AFG', 'BHS', 'BGD', 'BRB', 'BHR', 'BLZ', 'BLR', 'BEL', 'BEN', 'BMU', 'BGR', 'BOL', 'BES', 'BIH', 'BWA', 'BRA', 'IOT', 'VGB', 'BRN', 'BFA', 'BDI', 'BTN', 'VUT', 'VAT', 'GBR', 'HUN', 'VEN', 'UMI', 'TLS', 'VNM', 'GAB', 'HTI', 'GUY', 'GMB', 'GHA', 'GLP', 'GTM', 'GUF', 'GIN', 'GNB', 'DEU', 'GGY', 'GIB', 'HND', 'HKG', 'GRD', 'GRL', 'GRC', 'GEO', 'GUM', 'DNK', 'JEY', 'DJI', 'DMA', 'DOM', 'COD', 'EGY', 'ZMB', 'ESH', 'ZWE', 'ISR', 'IND', 'IDN', 'JOR', 'IRQ', 'IRN', 'IRL', 'ISL', 'ESP', 'ITA', 'YEM', 'CPV', 'KAZ', 'CYM', 'KHM', 'CMR', 'CAN', 'QAT', 'KEN', 'CYP', 'KGZ', 'KIR', 'TWN', 'PRK', 'CHN', 'CCK', 'COL', 'COM', 'CRI', 'CIV', 'CUB', 'KWT', 'CUW', 'LAO', 'LVA', 'LSO', 'LBR', 'LBN', 'LBY', 'LTU', 'LIE', 'LUX', 'MUS', 'MRT', 'MDG', 'MYT', 'MAC', 'MKD', 'MWI', 'MYS', 'MLI', 'MDV', 'MLT', 'MAR', 'MTQ', 'MHL', 'MEX', 'FSM', 'MOZ', 'MDA', 'MCO', 'MNG', 'MSR', 'MMR', 'NAM', 'NRU', 'NPL', 'NER', 'NGA', 'NLD', 'NIC', 'NIU', 'NZL', 'NCL', 'NOR', 'ARE', 'OMN', 'BVT', 'IMN', 'COK', 'NFK', 'CXR', 'PCN', 'SHN', 'PAK', 'PLW', 'PSE', 'PAN', 'PNG', 'PRY', 'PER', 'POL', 'PRT', 'PRI', 'COG', 'KOR', 'REU', 'RUS', 'RWA', 'ROU', 'SLV', 'WSM', 'SMR', 'STP', 'SAU', 'MNP', 'SYC', 'BLM', 'MAF', 'SPM', 'SEN', 'VCT', 'KNA', 'LCA', 'SRB', 'SGP', 'SXM', 'SYR', 'SVK', 'SVN', 'SLB', 'SOM', 'SDN', 'SUR', 'USA', 'SLE', 'TJK', 'THA', 'TZA', 'TCA', 'TGO', 'TKL', 'TON', 'TTO', 'TUV', 'TUN', 'TKM', 'TUR', 'UGA', 'UZB', 'UKR', 'WLF', 'URY', 'FRO', 'FJI', 'PHL', 'FIN', 'FLK', 'FRA', 'PYF', 'ATF', 'HMD', 'HRV', 'CAF', 'TCD', 'MNE', 'CZE', 'CHL', 'CHE', 'SWE', 'SJM', 'LKA', 'ECU', 'GNQ', 'ERI', 'SWZ', 'EST', 'ETH', 'ZAF', 'SGS', 'SSD', 'JAM', 'JPN', name='country', create_type=False), nullable=False),
    sa.Column('visa_id', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'ACCEPTED', 'COMPLETED', 'TRASH', name='visaformstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visas')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    sa.Enum('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='userrole').drop(op.get_bind())
    sa.Enum('AUS', 'AUT', 'AZE', 'ALA', 'ALB', 'DZA', 'VIR', 'ASM', 'AIA', 'AGO', 'AND', 'ATA', 'ATG', 'ARG', 'ARM', 'ABW', 'AFG', 'BHS', 'BGD', 'BRB', 'BHR', 'BLZ', 'BLR', 'BEL', 'BEN', 'BMU', 'BGR', 'BOL', 'BES', 'BIH', 'BWA', 'BRA', 'IOT', 'VGB', 'BRN', 'BFA', 'BDI', 'BTN', 'VUT', 'VAT', 'GBR', 'HUN', 'VEN', 'UMI', 'TLS', 'VNM', 'GAB', 'HTI', 'GUY', 'GMB', 'GHA', 'GLP', 'GTM', 'GUF', 'GIN', 'GNB', 'DEU', 'GGY', 'GIB', 'HND', 'HKG', 'GRD', 'GRL', 'GRC', 'GEO', 'GUM', 'DNK', 'JEY', 'DJI', 'DMA', 'DOM', 'COD', 'EGY', 'ZMB', 'ESH', 'ZWE', 'ISR', 'IND', 'IDN', 'JOR', 'IRQ', 'IRN', 'IRL', 'ISL', 'ESP', 'ITA', 'YEM', 'CPV', 'KAZ', 'CYM', 'KHM', 'CMR', 'CAN', 'QAT', 'KEN', 'CYP', 'KGZ', 'KIR', 'TWN', 'PRK', 'CHN', 'CCK', 'COL', 'COM', 'CRI', 'CIV', 'CUB', 'KWT', 'CUW', 'LAO', 'LVA', 'LSO', 'LBR', 'LBN', 'LBY', 'LTU', 'LIE', 'LUX', 'MUS', 'MRT', 'MDG', 'MYT', 'MAC', 'MKD', 'MWI', 'MYS', 'MLI', 'MDV', 'MLT', 'MAR', 'MTQ', 'MHL', 'MEX', 'FSM', 'MOZ', 'MDA', 'MCO', 'MNG', 'MSR', 'MMR', 'NAM', 'NRU', 'NPL', 'NER', 'NGA', 'NLD', 'NIC', 'NIU', 'NZL', 'NCL', 'NOR', 'ARE', 'OMN', 'BVT', 'IMN', 'COK', 'NFK', 'CXR', 'PCN', 'SHN', 'PAK', 'PLW', 'PSE', 'PAN', 'PNG', 'PRY', 'PER', 'POL', 'PRT', 'PRI', 'COG', 'KOR', 'REU', 'RUS', 'RWA', 'ROU', 'SLV', 'WSM', 'SMR', 'STP', 'SAU', 'MNP', 'SYC', 'BLM', 'MAF', 'SPM', 'SEN', 'VCT', 'KNA', 'LCA', 'SRB', 'SGP', 'SXM', 'SYR', 'SVK', 'SVN', 'SLB', 'SOM', 'SDN', 'SUR', 'USA', 'SLE', 'TJK', 'THA', 'TZA', 'TCA', 'TGO', 'TKL', 'TON', 'TTO', 'TUV', 'TUN', 'TKM', 'TUR', 'UGA', 'UZB', 'UKR', 'WLF', 'URY', 'FRO', 'FJI', 'PHL', 'FIN', 'FLK', 'FRA', 'PYF', 'ATF', 'HMD', 'HRV', 'CAF', 'TCD', 'MNE', 'CZE', 'CHL', 'CHE', 'SWE', 'SJM', 'LKA', 'ECU', 'GNQ', 'ERI', 'SWZ', 'EST', 'ETH', 'ZAF', 'SGS', 'SSD', 'JAM', 'JPN', name='country').drop(op.get_bind())
    sa.Enum('DRAFT', 'PENDING', 'ACCEPTED', 'COMPLETED', 'TRASH', name='visaformstatus').drop(op.get_bind())
    # ### end Alembic commands ###
