"""trash status

Revision ID: 312fe2ebb0fd
Revises: c045967bc413
Create Date: 2024-06-30 14:16:08.271991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '312fe2ebb0fd'
down_revision: str | None = 'c045967bc413'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'orderstatus', ['DRAFT', 'PENDING', 'ACCEPTED', 'COMPLETED', 'TRASH'],
                        [TableReference(table_schema='public', table_name='orders', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'orderstatus', ['TRASH', 'DRAFT', 'PENDING', 'ACCEPTED', 'COMPLETED'],
                        [TableReference(table_schema='public', table_name='orders', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
