"""Initial

Revision ID: ad4612fce4b3
Revises: 9fbdda96bfd6
Create Date: 2025-03-11 21:16:56.466871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'ad4612fce4b3'
down_revision: str | None = '9fbdda96bfd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'appformstatus', ['DRAFT', 'SAVED', 'PENDING', 'ACCEPTED', 'COMPLETED', 'TRASH'],
                        [TableReference(table_schema='public', table_name='app_forms', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'appformstatus', ['DRAFT', 'PENDING', 'ACCEPTED', 'COMPLETED', 'TRASH'],
                        [TableReference(table_schema='public', table_name='app_forms', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
