"""Initaial

Revision ID: f71162090e01
Revises: ad4612fce4b3
Create Date: 2025-05-02 16:53:57.720866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71162090e01'
down_revision: str | None = 'ad4612fce4b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
