server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker
  static_configs:
  - targets:
      - localhost
    labels:
      job: docker
      __path__: /var/lib/docker/containers/*/*-json.log
  pipeline_stages:
  - json:
      expressions:
        log: log
        stream: stream
        time: time
  - timestamp:
      source: time
      format: RFC3339Nano
  - output:
      source: log
