apiVersion: 1
contactPoints:
    - orgId: 1
      name: grafana-default-telegram
      receivers:
        - uid: fej6c0tkkegowa
          type: telegram
          settings:
            bottoken: $ALERT_BOT_TOKEN
            chatid: '${ALERT_BOT_CHATID:raw}'
            disable_notification: false
            disable_web_page_preview: false
            message: |-
                {{ define "__text_alert_list" }}{{ range . }}
                ⚠️ {{ .Annotations.summary }}
                {{ .Annotations.description }}
                {{ end }}{{ end }}
                {{ template "telegram.default.message" . }}
            parse_mode: None
            protect_content: false
          disableResolveMessage: false
