from enum import StrEnum, auto


# ISO 3166-2
class Country(StrEnum):
    AUS = auto()  # Австралия
    AUT = auto()  # Австрия
    AZE = auto()  # Азербайджан
    ALA = auto()  # Аландские острова
    ALB = auto()  # Албания
    DZA = auto()  # Алжир
    VIR = auto()  # Виргинские Острова (США)
    ASM = auto()  # Американское Самоа
    AIA = auto()  # Ангилья
    AGO = auto()  # Ангола
    AND = auto()  # Андорра
    ATA = auto()  # Антарктика
    ATG = auto()  # Антигуа и Барбуда
    ARG = auto()  # Аргентина
    ARM = auto()  # Армения
    ABW = auto()  # Аруба
    AFG = auto()  # Афганистан
    BHS = auto()  # Багамские Острова
    BGD = auto()  # Бангладеш
    BRB = auto()  # Барбадос
    BHR = auto()  # Бахрейн
    BLZ = auto()  # Белиз
    BLR = auto()  # Беларусь
    BEL = auto()  # Бельгия
    BEN = auto()  # Бенин
    BMU = auto()  # Бермуды
    BGR = auto()  # Болгария
    BOL = auto()  # Боливия
    BES = auto()  # Бонайре, Синт-Эстатиус и Саба
    BIH = auto()  # Босния и Герцеговина
    BWA = auto()  # Ботсвана
    BRA = auto()  # Бразилия
    IOT = auto()  # Британская Территория в Индийском Океане
    VGB = auto()  # Виргинские Острова (Великобритания)
    BRN = auto()  # Бруней
    BFA = auto()  # Буркина-Фасо
    BDI = auto()  # Бурунди
    BTN = auto()  # Бутан
    VUT = auto()  # Вануату
    VAT = auto()  # Ватикан
    GBR = auto()  # Великобритания
    HUN = auto()  # Венгрия
    VEN = auto()  # Венесуэла
    UMI = auto()  # Внешние малые острова США
    TLS = auto()  # Восточный Тимор
    VNM = auto()  # Вьетнам
    GAB = auto()  # Габон
    HTI = auto()  # Гаити
    GUY = auto()  # Гайана
    GMB = auto()  # Гамбия
    GHA = auto()  # Гана
    GLP = auto()  # Гваделупа
    GTM = auto()  # Гватемала
    GUF = auto()  # Гвиана
    GIN = auto()  # Гвинея
    GNB = auto()  # Гвинея-Бисау
    DEU = auto()  # Германия
    GGY = auto()  # Гернси
    GIB = auto()  # Гибралтар
    HND = auto()  # Гондурас
    HKG = auto()  # Гонконг
    GRD = auto()  # Гренада
    GRL = auto()  # Гренландия
    GRC = auto()  # Греция
    GEO = auto()  # Грузия
    GUM = auto()  # Гуам
    DNK = auto()  # Дания
    JEY = auto()  # Джерси
    DJI = auto()  # Джибути
    DMA = auto()  # Доминика
    DOM = auto()  # Доминиканская Республика
    COD = auto()  # ДР Конго
    EGY = auto()  # Египет
    ZMB = auto()  # Замбия
    ESH = auto()  # САДР
    ZWE = auto()  # Зимбабве
    ISR = auto()  # Израиль
    IND = auto()  # Индия
    IDN = auto()  # Индонезия
    JOR = auto()  # Иордания
    IRQ = auto()  # Ирак
    IRN = auto()  # Иран
    IRL = auto()  # Ирландия
    ISL = auto()  # Исландия
    ESP = auto()  # Испания
    ITA = auto()  # Италия
    YEM = auto()  # Йемен
    CPV = auto()  # Кабо-Верде
    KAZ = auto()  # Казахстан
    CYM = auto()  # Острова Кайман
    KHM = auto()  # Камбоджа
    CMR = auto()  # Камерун
    CAN = auto()  # Канада
    QAT = auto()  # Катар
    KEN = auto()  # Кения
    CYP = auto()  # Кипр
    KGZ = auto()  # Кыргызстан
    KIR = auto()  # Кирибати
    TWN = auto()  # Китайская Республика
    PRK = auto()  # КНДР (Корейская Народно-Демократическая Республика)
    CHN = auto()  # Китай (Китайская Народная Республика)
    CCK = auto()  # Кокосовые острова
    COL = auto()  # Колумбия
    COM = auto()  # Коморы
    CRI = auto()  # Коста-Рика
    CIV = auto()  # Кот-д’Ивуар
    CUB = auto()  # Куба
    KWT = auto()  # Кувейт
    CUW = auto()  # Кюрасао
    LAO = auto()  # Лаос
    LVA = auto()  # Латвия
    LSO = auto()  # Лесото
    LBR = auto()  # Либерия
    LBN = auto()  # Ливан
    LBY = auto()  # Ливия
    LTU = auto()  # Литва
    LIE = auto()  # Лихтенштейн
    LUX = auto()  # Люксембург
    MUS = auto()  # Маврикий
    MRT = auto()  # Мавритания
    MDG = auto()  # Мадагаскар
    MYT = auto()  # Майотта
    MAC = auto()  # Макао
    MKD = auto()  # Северная Македония
    MWI = auto()  # Малави
    MYS = auto()  # Малайзия
    MLI = auto()  # Мали
    MDV = auto()  # Мальдивы
    MLT = auto()  # Мальта
    MAR = auto()  # Марокко
    MTQ = auto()  # Мартиника
    MHL = auto()  # Маршалловы Острова
    MEX = auto()  # Мексика
    FSM = auto()  # Микронезия
    MOZ = auto()  # Мозамбик
    MDA = auto()  # Молдова
    MCO = auto()  # Монако
    MNG = auto()  # Монголия
    MSR = auto()  # Монтсеррат
    MMR = auto()  # Мьянма
    NAM = auto()  # Намибия
    NRU = auto()  # Науру
    NPL = auto()  # Непал
    NER = auto()  # Нигер
    NGA = auto()  # Нигерия
    NLD = auto()  # Нидерланды
    NIC = auto()  # Никарагуа
    NIU = auto()  # Ниуэ
    NZL = auto()  # Новая Зеландия
    NCL = auto()  # Новая Каледония
    NOR = auto()  # Норвегия
    ARE = auto()  # ОАЭ
    OMN = auto()  # Оман
    BVT = auto()  # Остров Буве
    IMN = auto()  # Остров Мэн
    COK = auto()  # Острова Кука
    NFK = auto()  # Остров Норфолк
    CXR = auto()  # Остров Рождества
    PCN = auto()  # Острова Питкэрн
    SHN = auto()  # Остров Святой Елены
    PAK = auto()  # Пакистан
    PLW = auto()  # Палау
    PSE = auto()  # Государство Палестина
    PAN = auto()  # Панама
    PNG = auto()  # Папуа — Новая Гвинея
    PRY = auto()  # Парагвай
    PER = auto()  # Перу
    POL = auto()  # Польша
    PRT = auto()  # Португалия
    PRI = auto()  # Пуэрто-Рико
    COG = auto()  # Республика Конго
    KOR = auto()  # Республика Корея
    REU = auto()  # Реюньон
    RUS = auto()  # Россия
    RWA = auto()  # Руанда
    ROU = auto()  # Румыния
    SLV = auto()  # Сальвадор
    WSM = auto()  # Самоа
    SMR = auto()  # Сан-Марино
    STP = auto()  # Сан-Томе и Принсипи
    SAU = auto()  # Саудовская Аравия
    MNP = auto()  # Северные Марианские Острова
    SYC = auto()  # Сейшельские Острова
    BLM = auto()  # Сен-Бартелеми
    MAF = auto()  # Сен-Мартен
    SPM = auto()  # Сен-Пьер и Микелон
    SEN = auto()  # Сенегал
    VCT = auto()  # Сент-Винсент и Гренадины
    KNA = auto()  # Сент-Китс и Невис
    LCA = auto()  # Сент-Люсия
    SRB = auto()  # Сербия
    SGP = auto()  # Сингапур
    SXM = auto()  # Синт-Мартен
    SYR = auto()  # Сирия
    SVK = auto()  # Словакия
    SVN = auto()  # Словения
    SLB = auto()  # Соломоновы Острова
    SOM = auto()  # Сомали
    SDN = auto()  # Судан
    SUR = auto()  # Суринам
    USA = auto()  # США
    SLE = auto()  # Сьерра-Леоне
    TJK = auto()  # Таджикистан
    THA = auto()  # Таиланд
    TZA = auto()  # Танзания
    TCA = auto()  # Теркс и Кайкос
    TGO = auto()  # Того
    TKL = auto()  # Токелау
    TON = auto()  # Тонга
    TTO = auto()  # Тринидад и Тобаго
    TUV = auto()  # Тувалу
    TUN = auto()  # Тунис
    TKM = auto()  # Туркменистан
    TUR = auto()  # Турция
    UGA = auto()  # Уганда
    UZB = auto()  # Узбекистан
    UKR = auto()  # Украина
    WLF = auto()  # Уоллис и Футуна
    URY = auto()  # Уругвай
    FRO = auto()  # Фарерские острова
    FJI = auto()  # Фиджи
    PHL = auto()  # Филиппины
    FIN = auto()  # Финляндия
    FLK = auto()  # Фолклендские острова
    FRA = auto()  # Франция
    PYF = auto()  # Французская Полинезия
    ATF = auto()  # Французские Южные и Антарктические территории
    HMD = auto()  # Херд и Макдональд
    HRV = auto()  # Хорватия
    CAF = auto()  # ЦАР
    TCD = auto()  # Чад
    MNE = auto()  # Черногория
    CZE = auto()  # Чехия
    CHL = auto()  # Чили
    CHE = auto()  # Швейцария
    SWE = auto()  # Швеция
    SJM = auto()  # Флаг Шпицбергена и Ян-Майена Шпицберген и Ян-Майен
    LKA = auto()  # Шри-Ланка
    ECU = auto()  # Эквадор
    GNQ = auto()  # Экваториальная Гвинея
    ERI = auto()  # Эритрея
    SWZ = auto()  # Эсватини
    EST = auto()  # Эстония
    ETH = auto()  # Эфиопия
    ZAF = auto()  # ЮАР
    SGS = auto()  # Южная Георгия и Южные Сандвичевы Острова
    SSD = auto()  # Южный Судан
    JAM = auto()  # Ямайка
    JPN = auto()  # Япония

