"""Initial

Revision ID: 93d45b736c59
Revises: 
Create Date: 2024-04-19 19:59:51.805433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93d45b736c59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='accesslevel').create(op.get_bind())
    sa.Enum('TRASH', 'DRAFT', 'PENDING', 'REVISION', 'ACCEPTED', 'SUBMITTED', 'REJECTED', 'ARCHIVED', name='orderstatus').create(op.get_bind())
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('access_level', postgresql.ENUM('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='accesslevel', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('TRASH', 'DRAFT', 'PENDING', 'REVISION', 'ACCEPTED', 'SUBMITTED', 'REJECTED', 'ARCHIVED', name='orderstatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    sa.Enum('TRASH', 'DRAFT', 'PENDING', 'REVISION', 'ACCEPTED', 'SUBMITTED', 'REJECTED', 'ARCHIVED', name='orderstatus').drop(op.get_bind())
    sa.Enum('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='accesslevel').drop(op.get_bind())
    # ### end Alembic commands ###
