version: '3.8'

volumes:
  grafana_data:

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    expose:
      - "8080"
    privileged: true
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - "9100"
    privileged: true
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    expose:
      - "9090"
    depends_on:
      - cadvisor
      - node-exporter
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.14
    container_name: promtail
    expose:
      - "9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    depends_on:
      - loki
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.14
    container_name: loki
    expose:
      - "3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - "13000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA__USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA__PASSWORD:-admin}
      - ALERT_BOT_TOKEN=${ALERT_BOT_TOKEN:-your_bot_token}
      - ALERT_BOT_CHATID=${ALERT_BOT_TOKEN:-your_chat_id}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/alert-rules.yaml:/etc/grafana/provisioning/alerting/alert-rules.yaml
      - ./grafana/notification-policies.yaml:/etc/grafana/provisioning/alerting/notification-policies.yaml
      - ./grafana/contact-points.yaml:/etc/grafana/provisioning/alerting/contact-points.yaml
    depends_on:
      - loki
      - prometheus
    restart: unless-stopped
