"""Order status

Revision ID: 6e326696ab27
Revises: 05fa5d1cabdf
Create Date: 2024-05-09 15:05:40.064395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '6e326696ab27'
down_revision: str | None = '05fa5d1cabdf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'orderstatus', ['TRASH', 'DRAFT', 'PENDING', 'ACCEPTED', 'COMPLETED'],
                        [TableReference(table_schema='public', table_name='orders', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'orderstatus', ['TRASH', 'DRAFT', 'ACCEPTED', 'COMPLETED'],
                        [TableReference(table_schema='public', table_name='orders', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
