from src.entities.form import Country

COUNTRY_FEATURED = [Country.RUS, Country.KAZ,
                    Country.BLR]

COUNTRY_FEATURED2 = [Country.THA, Country.VNM,
                     Country.LKA]

COUNTRY_ALL = list(Country)

COUNTRY_SAARC = [Country.AFG,
                 Country.BTN,
                 Country.PAK,
                 Country.MDV,
                 Country.BGD,
                 Country.LKA,
                 Country.NPL]

COUNTRY_FILTERED = [c for c in Country if c not in COUNTRY_SAARC and c != Country.IND]


COUNTRY_OUTPUT = {
    Country.AFG: "Афганистан",
    Country.ALB: "Албания",
    Country.AND: "Андорра",
    Country.AGO: "Ангола",
    Country.AIA: "Ангилья",
    Country.ATG: "Антигуа и Барбуда",
    Country.ARG: "Аргентина",
    Country.ARM: "Армения",
    Country.ABW: "Аруба",
    Country.AUS: "Австралия",
    Country.AUT: "Австрия",
    Country.AZE: "Азербайджан",
    Country.BHS: "Багамские острова",
    Country.BRB: "Барбадос",
    Country.BLR: "Беларусь",
    Country.BEL: "Бельгия",
    Country.BLZ: "Белиз",
    Country.BEN: "Бенин",
    Country.BOL: "Боливия",
    Country.BIH: "Босния и Герцеговина",
    Country.BWA: "Ботсвана",
    Country.BRA: "Бразилия",
    Country.BRN: "Бруней",
    Country.BGR: "Болгария",
    Country.BDI: "Бурунди",
    Country.KHM: "Камбоджа",
    Country.CMR: "Камерун",
    Country.CAN: "Канада",
    Country.CPV: "Кабо-Верде",
    Country.CYM: "Каймановы острова",
    Country.CHL: "Чили",
    Country.CHN: "Китай",
    Country.HKG: "Гонконг",
    Country.MAC: "Макао",
    Country.COL: "Колумбия",
    Country.COM: "Коморские острова",
    Country.COK: "Острова Кука",
    Country.CRI: "Коста-Рика",
    Country.CIV: "Кот-д'Ивуар",
    Country.HRV: "Хорватия",
    Country.CUB: "Куба",
    Country.CYP: "Кипр",
    Country.CZE: "Чехия",
    Country.DNK: "Дания",
    Country.DJI: "Джибути",
    Country.DMA: "Доминика",
    Country.DOM: "Доминиканская Республика",
    Country.TLS: "Восточный Тимор",
    Country.ECU: "Эквадор",
    Country.SLV: "Сальвадор",
    Country.GNQ: "Экваториальная Гвинея",
    Country.ERI: "Эритрея",
    Country.EST: "Эстония",
    Country.SWZ: "Эсватини",
    Country.FJI: "Фиджи",
    Country.FIN: "Финляндия",
    Country.FRA: "Франция",
    Country.GAB: "Габон",
    Country.GMB: "Гамбия",
    Country.GEO: "Грузия",
    Country.DEU: "Германия",
    Country.GHA: "Гана",
    Country.GIB: "Гибралтар",
    Country.GRC: "Греция",
    Country.GRD: "Гренада",
    Country.GTM: "Гватемала",
    Country.GGY: "Гернси",
    Country.GIN: "Гвинея",
    Country.GUY: "Гайана",
    Country.HTI: "Гаити",
    Country.HND: "Гондурас",
    Country.HUN: "Венгрия",
    Country.ISL: "Исландия",
    Country.IDN: "Индонезия",
    Country.IRL: "Ирландия",
    Country.IMN: "Остров Мэн",
    Country.ISR: "Израиль",
    Country.ITA: "Италия",
    Country.JAM: "Ямайка",
    Country.JPN: "Япония",
    Country.JEY: "Джерси",
    Country.JOR: "Иордания",
    Country.KAZ: "Казахстан",
    Country.KEN: "Кения",
    Country.KIR: "Кирибати",
    Country.KGZ: "Кыргызстан",
    Country.LAO: "Лаос",
    Country.LVA: "Латвия",
    Country.LSO: "Лесото",
    Country.LBR: "Либерия",
    Country.LIE: "Лихтенштейн",
    Country.LTU: "Литва",
    Country.LUX: "Люксембург",
    Country.MDG: "Мадагаскар",
    Country.MWI: "Малави",
    Country.MYS: "Малайзия",
    Country.MLI: "Мали",
    Country.MLT: "Мальта",
    Country.MHL: "Маршалловы острова",
    Country.MUS: "Маврикий",
    Country.MEX: "Мексика",
    Country.FSM: "Микронезия",
    Country.MDA: "Молдова",
    Country.MCO: "Монако",
    Country.MNG: "Монголия",
    Country.MNE: "Черногория",
    Country.MSR: "Монтсеррат",
    Country.MAR: "Марокко",
    Country.MOZ: "Мозамбик",
    Country.MMR: "Мьянма",
    Country.NAM: "Намибия",
    Country.NRU: "Науру",
    Country.NLD: "Нидерланды",
    Country.NZL: "Новая Зеландия",
    Country.NIC: "Никарагуа",
    Country.NER: "Нигер",
    Country.NIU: "Ниуэ Остров",
    Country.NOR: "Норвегия",
    Country.OMN: "Оман",
    Country.PLW: "Палау",
    Country.PSE: "Палестина",
    Country.PAN: "Панама",
    Country.PNG: "Папуа Новая Гвинея",
    Country.PRY: "Парагвай",
    Country.PER: "Перу",
    Country.PHL: "Филиппины",
    Country.POL: "Польша",
    Country.PRT: "Португалия",
    Country.KOR: "Республика Корея",
    Country.MKD: "Республика Северная Македония",
    Country.ROU: "Румыния",
    Country.RUS: "Россия",
    Country.RWA: "Руанда",
    Country.KNA: "Сент-Китс и Невис",
    Country.LCA: "Сент-Люсия",
    Country.VCT: "Сент-Винсент и Гренадины",
    Country.SMR: "Сан-Марино",
    Country.SAU: "Саудовская Аравия",
    Country.SEN: "Сенегал",
    Country.SRB: "Сербия",
    Country.SYC: "Сейшельские острова",
    Country.SLE: "Сьерра-Леоне",
    Country.SGP: "Сингапур",
    Country.SVK: "Словакия",
    Country.SVN: "Словения",
    Country.SLB: "Соломоновы острова",
    Country.ZAF: "Южная Африка",
    Country.ESP: "Испания",
    Country.LKA: "Шри-Ланка",
    Country.SUR: "Суринам",
    Country.SWE: "Швеция",
    Country.CHE: "Швейцария",
    Country.TWN: "Тайвань",
    Country.TJK: "Таджикистан",
    Country.TZA: "Танзания",
    Country.THA: "Таиланд",
    Country.TGO: "Того",
    Country.TON: "Тонга",
    Country.TTO: "Тринидад и Тобаго",
    Country.TCA: "Теркс и Кайкос острова",
    Country.TUV: "Тувалу",
    Country.UGA: "Уганда",
    Country.UKR: "Украина",
    Country.ARE: "Объединенные Арабские Эмираты",
    Country.GBR: "Великобритания",
    Country.USA: "Соединенные Штаты Америки",
    Country.URY: "Уругвай",
    Country.UZB: "Узбекистан",
    Country.VUT: "Вануату",
    Country.VAT: "Ватикан",
    Country.VEN: "Венесуэла",
    Country.VNM: "Вьетнам",
    Country.WSM: "Западное Самоа",
    Country.ZMB: "Замбия",
    Country.ZWE: "Зимбабве",

    Country.IND: "Индия",
    Country.BTN: "Бутан",
    Country.PAK: "Пакистан",
    Country.MDV: "Мальдивы",
    Country.BGD: "Бангладеш",
    Country.NPL: "Непал"
}
