from src.entities.form import PortInd

PORT_IND_ALL = list(PortInd)

PORT_IND_DEFAULT = [PortInd.I033,
                    PortInd.I034,
                    PortInd.I004,
                    PortInd.I001]

PORT_IND_OUTPUT = {
    PortInd.I022: "Аэропорт Ахмедабад",
    PortInd.I032: "Аэропорт Амритсар",
    PortInd.I096: "Аэропорт Багдогра",
    PortInd.I085: "Аэропорт Бенгалуру",
    PortInd.I084: "Аэропорт Бхубанешвар",
    PortInd.I010: "Аэропорт Каликут",
    PortInd.I005: "Аэропорт Чандигарх",
    PortInd.I008: "Аэропорт Ченнай",
    PortInd.I208: "Морской Порт Ченнай",
    PortInd.I024: "Аэропорт Кочин",
    PortInd.I224: "Морской Порт Кочин",
    PortInd.I094: "Аэропорт Коимбаторе",
    PortInd.I004: "Аэропорт Дели",
    PortInd.I012: "Аэропорт Гайя",
    PortInd.I033: "Аэропорт Гоа (Даболим)",
    PortInd.I034: "Аэропорт Гоа (Мопа)",
    PortInd.I283: "Морской Порт Гоа",
    PortInd.I019: "Аэропорт Гувахати",
    PortInd.I041: "Аэропорт Хайдерабад",
    PortInd.I017: "Аэропорт Индор",
    PortInd.I006: "Аэропорт Джайпур",
    PortInd.I030: "Аэропорт Каннур",
    PortInd.I002: "Аэропорт Колката",
    PortInd.I021: "Аэропорт Удачноу",
    PortInd.I015: "Аэропорт Мадурай",
    PortInd.I092: "Аэропорт Мангалор",
    PortInd.I293: "Морской Порт Мангалор",
    PortInd.I001: "Аэропорт Мумбаи",
    PortInd.I201: "Морской Порт Мумбаи",
    PortInd.I016: "Аэропорт Нагпур",
    PortInd.I077: "Аэропорт Портблейр",
    PortInd.I277: "Морской Порт Портблейр",
    PortInd.I026: "Аэропорт Пуна",
    PortInd.I003: "Аэропорт Тиручирапалли",
    PortInd.I023: "Аэропорт Тривандрум",
    PortInd.I007: "Аэропорт Варанаси",
    PortInd.I025: "Аэропорт Вишакхапатнам",
}
