"""Datetime added

Revision ID: b31b9c2e2376
Revises: f7765d47e1b9
Create Date: 2024-05-07 16:27:01.106904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31b9c2e2376'
down_revision: str | None = 'f7765d47e1b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created', sa.DateTime(timezone=True), nullable=False))
    op.add_column('orders', sa.Column('updated', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('created', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('updated', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created')
    op.drop_column('orders', 'updated')
    op.drop_column('orders', 'created')
    # ### end Alembic commands ###
