"""Order status

Revision ID: 05fa5d1cabdf
Revises: b31b9c2e2376
Create Date: 2024-05-09 12:10:03.201027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '05fa5d1cabdf'
down_revision: str | None = 'b31b9c2e2376'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'orderstatus', ['TRASH', 'DRAFT', 'ACCEPTED', 'COMPLETED'],
                        [TableReference(table_schema='public', table_name='orders', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'orderstatus', ['TRASH', 'DRAFT', 'PENDING', 'REVISION', 'ACCEPTED', 'SUBMITTED', 'REJECTED', 'ARCHIVED'],
                        [TableReference(table_schema='public', table_name='orders', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
