"""User role

Revision ID: c045967bc413
Revises: 6e326696ab27
Create Date: 2024-05-09 22:07:01.188353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c045967bc413'
down_revision: str | None = '6e326696ab27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='userrole').create(op.get_bind())
    op.add_column('users', sa.Column('role', postgresql.ENUM('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='userrole', create_type=False), nullable=False))
    op.drop_column('users', 'access_level')
    sa.Enum('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='accesslevel').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='accesslevel').create(op.get_bind())
    op.add_column('users', sa.Column('access_level', postgresql.ENUM('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='accesslevel', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    sa.Enum('BLOCKED', 'USER', 'AGENT', 'ADMINISTRATOR', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
